# SwarmPod Rails Application Template
# Usage: rails new myapp --template path/to/rails_swarmpod.rb

# Generate the home controller
generate(:controller, "home index")

# Set root route
route 'root "home#index"'

# Remove the default route generated by the controller generator
gsub_file "config/routes.rb", /  get "home\/index"\n/, ""

# Create the home page view
file "app/views/home/index.html.erb", <<-'HTML'
<style>
  :root {
    --navy: #1a1a2e;
    --teal: #16213e;
    --accent: #e94560;
    --gold: #f5c518;
    --light: #eaeaea;
    --green: #2ecc71;
  }

  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: var(--navy);
    color: var(--light);
  }

  .hero {
    text-align: center;
    padding: 80px 20px 40px;
    background: linear-gradient(135deg, var(--navy), var(--teal));
  }

  .hero h1 {
    font-size: 3rem;
    margin: 0 0 10px;
    color: #fff;
  }

  .hero h1 .rails { color: var(--accent); }
  .hero h1 .swarm { color: var(--gold); }

  .hero .tagline {
    font-size: 1.3rem;
    color: #ccc;
    max-width: 700px;
    margin: 0 auto 30px;
    line-height: 1.6;
  }

  .hero .highlight {
    display: inline-block;
    background: var(--accent);
    color: #fff;
    padding: 8px 24px;
    border-radius: 6px;
    font-size: 1.1rem;
    font-weight: 600;
    margin-top: 10px;
  }

  .lessons {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    gap: 30px;
    padding: 60px 20px;
    max-width: 960px;
    margin: 0 auto;
  }

  .lesson-card {
    background: var(--teal);
    border: 1px solid #2a2a4a;
    border-radius: 12px;
    padding: 30px;
    width: 260px;
    text-align: center;
    transition: transform 0.2s, box-shadow 0.2s;
  }

  .lesson-card:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 30px rgba(0, 0, 0, 0.4);
  }

  .lesson-number {
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 2px;
    color: var(--gold);
    margin-bottom: 10px;
  }

  .lesson-card h2 {
    font-size: 1.5rem;
    margin: 0 0 12px;
    color: #fff;
  }

  .lesson-card p {
    font-size: 0.95rem;
    color: #aaa;
    line-height: 1.5;
  }

  .lesson-card.secrets  { border-top: 3px solid var(--accent); }
  .lesson-card.docker   { border-top: 3px solid #3498db; }
  .lesson-card.github   { border-top: 3px solid var(--green); }

  .modular {
    text-align: center;
    padding: 40px 20px 80px;
    max-width: 700px;
    margin: 0 auto;
  }

  .modular h2 {
    font-size: 1.6rem;
    color: var(--gold);
    margin-bottom: 12px;
  }

  .modular p {
    color: #aaa;
    font-size: 1.05rem;
    line-height: 1.6;
  }

  .modular a {
    color: var(--accent);
    text-decoration: none;
    font-weight: 600;
  }

  .modular a:hover {
    text-decoration: underline;
  }

  .footer {
    text-align: center;
    padding: 20px;
    font-size: 0.85rem;
    color: #555;
    border-top: 1px solid #2a2a4a;
  }
</style>

<section class="hero">
  <h1><span class="rails">Rails</span> + <span class="swarm">SwarmPod</span></h1>
  <p class="tagline">
    <strong>SwarmPod</strong> brings
    <strong>Multi-Repository Agentic Programming Skills</strong>
    to you in <strong>1 hour</strong>.
  </p>
  <span class="highlight">Start building with agents today</span>
</section>

<section class="lessons">
  <div class="lesson-card secrets">
    <div class="lesson-number">Lesson 1</div>
    <h2>Secrets</h2>
    <p>
      Learn how to manage API keys and credentials safely.
      SwarmPod Core loads secrets from your local filesystem or environment
      variables &mdash; never committed to version control.
    </p>
  </div>

  <div class="lesson-card docker">
    <div class="lesson-number">Lesson 2</div>
    <h2>Docker Desktop</h2>
    <p>
      Package your entire development environment into containers.
      One command to spin up databases, services, and your Rails app
      together.
    </p>
  </div>

  <div class="lesson-card github">
    <div class="lesson-number">Lesson 3</div>
    <h2>GitHub</h2>
    <p>
      Collaborate across multiple repositories with pull requests,
      actions, and agentic workflows that keep your team in sync.
    </p>
  </div>
</section>

<section class="modular">
  <h2>Everything Else Is Modular</h2>
  <p>
    All additional lessons and tools are freely available on the
    <a href="https://github.com/CbiPerson" target="_blank">CbiPerson</a>
    GitHub repository. Pick what you need, skip what you don't.
  </p>
</section>

<footer class="footer">
  Powered by Ruby on Rails &amp; SwarmPod
</footer>
HTML
