# SwarmPod Rails Application Template
# Usage: rails new myapp --template path/to/rails_swarmpod.rb

# Generate the home controller
generate(:controller, "home index")

# Generate the next controller
generate(:controller, "next index")

# Set root route
route 'root "home#index"'

# Add next route
route 'get "next", to: "next#index"'

# Remove the default routes generated by the controller generators
gsub_file "config/routes.rb", /  get "home\/index"\n/, ""
gsub_file "config/routes.rb", /  get "next\/index"\n/, ""

# Create the home page view
file "app/views/home/index.html.erb", <<-'HTML'
<style>
  :root {
    --navy: #1a1a2e;
    --teal: #16213e;
    --accent: #e94560;
    --gold: #f5c518;
    --light: #eaeaea;
    --green: #2ecc71;
  }

  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: var(--navy);
    color: var(--light);
  }

  .hero {
    text-align: center;
    padding: 80px 20px 40px;
    background: linear-gradient(135deg, var(--navy), var(--teal));
  }

  .hero h1 {
    font-size: 3rem;
    margin: 0 0 10px;
    color: #fff;
  }

  .hero h1 .rails { color: var(--accent); }
  .hero h1 .swarm { color: var(--gold); }

  .hero .tagline {
    font-size: 1.3rem;
    color: #ccc;
    max-width: 700px;
    margin: 0 auto 30px;
    line-height: 1.6;
  }

  .hero .highlight {
    display: inline-block;
    background: var(--accent);
    color: #fff;
    padding: 8px 24px;
    border-radius: 6px;
    font-size: 1.1rem;
    font-weight: 600;
    margin-top: 10px;
  }

  .lessons {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    gap: 30px;
    padding: 60px 20px;
    max-width: 960px;
    margin: 0 auto;
  }

  .lesson-card {
    background: var(--teal);
    border: 1px solid #2a2a4a;
    border-radius: 12px;
    padding: 30px;
    width: 260px;
    text-align: center;
    transition: transform 0.2s, box-shadow 0.2s;
  }

  .lesson-card:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 30px rgba(0, 0, 0, 0.4);
  }

  a.lesson-link {
    text-decoration: none;
    color: inherit;
  }

  .lesson-number {
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 2px;
    color: var(--gold);
    margin-bottom: 10px;
  }

  .lesson-card h2 {
    font-size: 1.5rem;
    margin: 0 0 12px;
    color: #fff;
  }

  .lesson-card p {
    font-size: 0.95rem;
    color: #aaa;
    line-height: 1.5;
  }

  .lesson-card.secrets  { border-top: 3px solid var(--accent); }
  .lesson-card.docker   { border-top: 3px solid #3498db; }
  .lesson-card.github   { border-top: 3px solid var(--green); }

  .modular {
    text-align: center;
    padding: 40px 20px 80px;
    max-width: 700px;
    margin: 0 auto;
  }

  .modular h2 {
    font-size: 1.6rem;
    color: var(--gold);
    margin-bottom: 12px;
  }

  .modular p {
    color: #aaa;
    font-size: 1.05rem;
    line-height: 1.6;
  }

  .modular a {
    color: var(--accent);
    text-decoration: none;
    font-weight: 600;
  }

  .modular a:hover {
    text-decoration: underline;
  }

  .next-section {
    text-align: center;
    padding: 0 20px 60px;
    max-width: 700px;
    margin: 0 auto;
  }

  .next-section a {
    display: inline-block;
    background: var(--gold);
    color: var(--navy);
    padding: 14px 36px;
    border-radius: 8px;
    font-size: 1.2rem;
    font-weight: 700;
    text-decoration: none;
    transition: transform 0.2s, box-shadow 0.2s;
  }

  .next-section a:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 20px rgba(245, 197, 24, 0.3);
  }

  .footer {
    text-align: center;
    padding: 20px;
    font-size: 0.85rem;
    color: #555;
    border-top: 1px solid #2a2a4a;
  }
</style>

<section class="hero">
  <h1><span class="rails">Rails</span> + <span class="swarm">SwarmPod</span></h1>
  <p class="tagline">
    <strong>SwarmPod</strong> brings
    <strong>Multi-Repository Agentic Programming Skills</strong>
    to you in <strong>1 hour</strong>.
  </p>
  <span class="highlight">Start building with agents today</span>
</section>

<section class="lessons">
  <a href="http://folkcoder.com/swarmpod/landing" class="lesson-link">
    <div class="lesson-card secrets">
      <div class="lesson-number">Lesson 1</div>
      <h2>Secrets</h2>
      <p>
        Learn how to manage API keys and credentials safely.
        SwarmPod Core loads secrets from your local filesystem or environment
        variables &mdash; never committed to version control.
      </p>
    </div>
  </a>

  <a href="http://folkcoder.com/swarmpod/landing" class="lesson-link">
    <div class="lesson-card docker">
      <div class="lesson-number">Lesson 2</div>
      <h2>Docker Desktop</h2>
      <p>
        Package your entire development environment into containers.
        One command to spin up databases, services, and your Rails app
        together.
      </p>
    </div>
  </a>

  <a href="http://folkcoder.com/swarmpod/landing" class="lesson-link">
    <div class="lesson-card github">
      <div class="lesson-number">Lesson 3</div>
      <h2>GitHub</h2>
      <p>
        Collaborate across multiple repositories with pull requests,
        actions, and agentic workflows that keep your team in sync.
      </p>
    </div>
  </a>
</section>

<section class="modular">
  <h2>Everything Else Is Modular</h2>
  <p>
    All additional lessons and tools are freely available on the
    <a href="https://github.com/CbiPerson" target="_blank">CbiPerson</a>
    GitHub repository. Pick what you need, skip what you don't.
  </p>
</section>

<section class="next-section">
  <a href="/next">What&rsquo;s Next?</a>
</section>

<footer class="footer">
  Powered by Ruby on Rails &amp; SwarmPod
</footer>
HTML

# Create the next page view
file "app/views/next/index.html.erb", <<-'HTML'
<style>
  :root {
    --navy: #1a1a2e;
    --teal: #16213e;
    --accent: #e94560;
    --gold: #f5c518;
    --light: #eaeaea;
    --green: #2ecc71;
  }

  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: var(--navy);
    color: var(--light);
  }

  .next-page {
    max-width: 740px;
    margin: 0 auto;
    padding: 60px 20px 80px;
  }

  .next-page h1 {
    font-size: 2.4rem;
    color: var(--gold);
    margin-bottom: 10px;
  }

  .next-page h1 span {
    color: #fff;
  }

  .next-page .subtitle {
    font-size: 1.15rem;
    color: #aaa;
    margin-bottom: 50px;
    line-height: 1.6;
  }

  .next-page h2 {
    font-size: 1.5rem;
    color: var(--accent);
    margin-top: 50px;
    margin-bottom: 12px;
  }

  .next-page p {
    font-size: 1.05rem;
    color: #ccc;
    line-height: 1.7;
    margin-bottom: 16px;
  }

  .next-page strong {
    color: #fff;
  }

  .next-page .architecture-list {
    list-style: none;
    padding: 0;
    margin: 20px 0;
  }

  .next-page .architecture-list li {
    padding: 8px 0;
    font-size: 1.05rem;
    color: #ccc;
    border-bottom: 1px solid #2a2a4a;
  }

  .next-page .architecture-list li:last-child {
    border-bottom: none;
  }

  .next-page .architecture-list li strong {
    color: var(--gold);
  }

  .register-cta {
    text-align: center;
    margin-top: 50px;
    padding: 40px;
    background: var(--teal);
    border: 1px solid #2a2a4a;
    border-radius: 12px;
  }

  .register-cta h2 {
    margin-top: 0;
    color: var(--gold);
  }

  .register-cta a {
    display: inline-block;
    background: var(--accent);
    color: #fff;
    padding: 14px 36px;
    border-radius: 8px;
    font-size: 1.15rem;
    font-weight: 700;
    text-decoration: none;
    margin-top: 16px;
    transition: transform 0.2s, box-shadow 0.2s;
  }

  .register-cta a:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 20px rgba(233, 69, 96, 0.3);
  }

  .back-link {
    display: block;
    text-align: center;
    margin-top: 40px;
    color: #666;
    font-size: 0.95rem;
  }

  .back-link a {
    color: var(--accent);
    text-decoration: none;
  }

  .back-link a:hover {
    text-decoration: underline;
  }
</style>

<div class="next-page">
  <h1><span>Congratulations!</span></h1>
  <p class="subtitle">
    You just built a working Rails application with a single command.
    Welcome to SwarmPod.
  </p>

  <h2>&ldquo;Wait, what just happened?&rdquo;</h2>
  <p>
    You clicked a lesson card and landed on a registration page. The app
    itself looks deceptively simple &mdash; three cards, a footer, done.
    That feeling of <strong>&ldquo;is that it?&rdquo;</strong> is intentional.
  </p>
  <p>
    What actually happened is more interesting: you ran
    <strong>rails new --template</strong> and a fully structured application
    appeared &mdash; styled, routed, and ready. No scaffolding tutorials.
    No copy-paste setup guides. One command.
  </p>

  <h2>Why it&rsquo;s built this way</h2>
  <p>
    The simplicity IS the lesson. Every architectural choice here is deliberate:
  </p>
  <ul class="architecture-list">
    <li><strong>Multi-repo</strong> &mdash; each concern lives in its own repository, just like real teams ship software</li>
    <li><strong>Modular gems</strong> &mdash; SwarmPod Core is a Ruby gem, not a monolith feature</li>
    <li><strong>Secrets outside the repo</strong> &mdash; credentials never touch version control</li>
    <li><strong>Containerized environments</strong> &mdash; Docker Compose makes &ldquo;works on my machine&rdquo; a guarantee, not an excuse</li>
    <li><strong>Template-driven setup</strong> &mdash; one command creates a consistent starting point for every team member</li>
  </ul>
  <p>
    You just ran <strong>rails new --template</strong> and had a working app.
    That&rsquo;s agentic programming &mdash; letting tools do the setup work
    so you can focus on building.
  </p>

  <div class="register-cta">
    <h2>Start the Curriculum</h2>
    <p>
      Register at FolkCoder to unlock the full SwarmPod curriculum.
      We&rsquo;ll track your progress through Secrets, Docker, GitHub,
      and beyond.
    </p>
    <a href="http://folkcoder.com/swarmpod/landing">Register &amp; Begin</a>
  </div>

  <p class="back-link">
    <a href="/">&larr; Back to home</a>
  </p>
</div>
HTML
